plugins { id 'com.android.application' }

android {
    namespace 'dev.bendmobile'
    compileSdk 36
    ndkVersion '27.1.12297006'
    defaultConfig {
        applicationId 'dev.bendmobile.counter'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '0.1'
        testInstrumentationRunner 'dev.bendmobile.ComputeInstrumentation'
        externalNativeBuild { cmake { cppFlags '-std=c++17 -fexceptions' } }
    }
    externalNativeBuild { cmake { path 'src/main/cpp/CMakeLists.txt' } }
}
